config: conf/train_asr.yaml
print_config: false
log_level: INFO
drop_last_iter: false
dry_run: false
iterator_type: sequence
valid_iterator_type: null
output_dir: exp/marathi_asr
ngpu: 1
seed: 0
num_workers: 4
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: null
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
use_deepspeed: false
deepspeed_config: null
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
use_tf32: false
collect_stats: false
write_collected_feats: false
max_epoch: 40
patience: 3
val_scheduler_criterion:
- valid
- loss
- min
early_stopping_criterion:
- valid
- loss
- min
- 3
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models:
- 10
nbest_averaging_interval: 0
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: false
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
use_adapter: false
adapter: lora
save_strategy: all
adapter_conf: {}
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 16
valid_batch_size: null
batch_bins: 1000000
valid_batch_bins: null
category_sample_size: 10
train_shape_file:
- data/train/speech.scp.shape
valid_shape_file:
- data/valid/speech.scp.shape
batch_type: folded
valid_batch_type: null
fold_length:
- 160000
sort_in_batch: descending
shuffle_within_batch: false
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
chunk_excluded_key_prefixes: []
chunk_default_fs: null
chunk_max_abs_length: null
chunk_discard_short_samples: true
train_data_path_and_name_and_type:
-   - data/train/wav.scp
    - speech
    - sound
-   - data/train/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - data/valid/wav.scp
    - speech
    - sound
-   - data/valid/text
    - text
    - text
multi_task_dataset: false
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
allow_multi_rates: false
valid_max_cache_size: null
exclude_weight_decay: false
exclude_weight_decay_conf: {}
optim: adam
optim_conf:
    lr: 0.0001
scheduler: null
scheduler_conf: {}
token_list:
- <unk>
- <s>
- </s>
- .
- ा
- े
- ी
- ▁
- र
- त
- न
- क
- म
- ि
- स
- ल
- ▁आहे
- व
- ▁व
- ं
- च
- ▁या
- प
- ','
- ला
- ात
- ु
- ो
- ण
- ्
- य
- ग
- ▁स
- ्या
- ▁अ
- ▁आ
- ट
- ू
- ळ
- च्या
- ▁क
- ्य
- ले
- र्
- ▁हे
- ज
- श
- ध
- द
- चे
- चा
- ▁म
- ड
- ▁प
- ली
- ने
- भ
- ▁द
- ▁हा
- ही
- ून
- ील
- ्र
- ▁एक
- िक
- ▁ज
- ▁त्या
- ाच्या
- ▁ब
- ▁आणि
- ित
- वर
- ाचे
- ख
- ह
- ▁होते
- ▁र
- ▁न
- ▁प्र
- थ
- ातील
- ▁आहेत
- ब
- ची
- ाचा
- वा
- ▁श
- ंग
- ाची
- ाने
- ती
- ▁असे
- ▁ही
- ार
- ▁वि
- ष
- री
- ंड
- ता
- ंद
- ▁सर्व
- ाला
- ▁सं
- ना
- ास
- ▁होता
- ▁ह
- ल्या
- ▁ते
- ▁भ
- रा
- ▁ख
- ▁राज्य
- ▁पा
- क्ष
- त्र
- ▁त
- ठ
- ंत
- स्त
- ▁सा
- ▁च
- ▁उ
- ▁ग
- ▁नाही
- ▁नाव
- मध्ये
- ▁केले
- ावर
- वि
- कार
- ▁अनेक
- ▁नि
- कर
- ▁मा
- ▁वा
- ▁य
- घ
- ान
- ते
- ांनी
- णी
- दा
- ाव
- ांना
- ां
- ै
- ढ
- वी
- ▁ल
- ▁हो
- ▁झाले
- ▁भारत
- का
- ▁इ
- ृ
- ौ
- ▁जाते
- ▁म्हणून
- ▁ध
- ण्या
- ▁सु
- ▁ना
- ▁का
- ▁ती
- ▁होती
- ंब
- ▁तो
- ▁कु
- हा
- ाळ
- ▁गो
- ीय
- ▁फ
- शी
- ▁बा
- ▁ति
- ▁ला
- ांच्या
- ्म
- सा
- वे
- फ
- ांचे
- ▁देश
- ऊ
- ोड
- ▁शहर
- ▁मान
- ▁राज
- ▁केली
- ▁त्यांनी
- ▁राम
- रे
- णा
- मान
- ▁केला
- णार
- त्य
- ▁कर
- प्र
- साठी
- ▁मु
- ांत
- ॉ
- ▁घ
- तो
- क्त
- ▁जा
- ▁काही
- ष्ट
- ▁म्हणजे
- ▁पर
- तात
- ▁ट
- मध
- ▁झाला
- प्रमुख
- ीत
- ▁येथे
- ▁पक्ष
- ांची
- ▁असा
- ▁लोक
- ▁उप
- िन
- ▁भारतीय
- ▁प्रा
- ▁ह्या
- तील
- ोर
- ▁तर
- ▁ता
- जी
- ▁शि
- ंचा
- रण
- ▁देव
- ▁त्यांना
- ▁चंद्र
- दी
- झ
- िय
- ▁भाग
- ांचा
- टी
- णे
- ▁भा
- ▁येथ
- ्स
- ▁महाभारत
- ांमध्ये
- हि
- ▁गु
- ण्यासाठी
- के
- बा
- ▁राष्ट्र
- ▁कि
- ▁त्याला
- द्
- पासून
- ▁असलेल
- ▁दु
- र्थ
- ▁त्यांच्या
- न्
- ▁खा
- ▁उद
- ▁स्व
- व्या
- ▁लेख
- ▁महा
- स्थ
- ॅ
- ुन
- मुळे
- कडे
- ▁राजा
- ▁गा
- नंतर
- ▁हि
- ▁तसे
- ▁आपल्या
- ▁होत
- ▁को
- ▁काम
- ▁त्याच्या
- ▁घेत
- ▁धर्म
- ▁दोन
- ▁काळ
- ▁थ
- ाई
- ्ह
- ▁मिळ
- पूर
- न्न
- ▁आज
- ▁पि
- शास्त्र
- ▁यांच्या
- ▁त्यामुळे
- ▁भाषा
- ▁महाराष्ट्र
- ▁पण
- ▁उत्तर
- राम
- त्त
- ▁ठेव
- ▁म्हणतात
- ▁दिले
- ▁पुर
- ▁पुत्र
- ज्ञ
- ▁झाली
- ▁शिक्षण
- ई
- लेल्या
- नी
- ातून
- ▁मो
- ▁इतर
- ▁जातो
- ▁अर्थ
- से
- ▁जग
- ▁करून
- ▁पद
- ▁ने
- पर्यंत
- नाथ
- ▁नदी
- िया
- ▁आई
- ▁रामायण
- श्र
- धार
- ▁किंवा
- देश
- रूप
- जवळ
- द्ध
- ▁पो
- ▁प्रसिद्ध
- ▁असल्या
- ूर
- ▁संघ
- ▁त्याने
- व्ह
- ्यात
- ोप
- ▁आले
- ▁सूर्य
- ▁सरकार
- ▁चाल
- वास
- ▁अस
- ▁गेले
- या
- ▁युद्ध
- ▁त्यांचे
- ▁मराठी
- ▁भारतात
- ▁अशा
- ाह
- ासाठी
- ▁प्रदेश
- ▁सम
- ▁समज
- ▁एका
- िका
- ळे
- ुर
- ▁राह
- ंची
- जन
- डी
- ▁संत
- ▁वापर
- ▁जन्म
- द्य
- ▁असते
- ▁दे
- ▁अशी
- ▁पड
- योग
- ृत
- ▁वर्ष
- ▁सह
- कडून
- वाद
- ▁म्हण
- ▁ठिकाण
- ▁मि
- डा
- प्रमाणे
- ▁आपल
- की
- ▁चि
- ▁जिल्ह्यात
- त्व
- ▁ये
- ▁होतो
- ▁ए
- ल्ल
- ▁शा
- ंनी
- ▁जे
- ेल
- ▁राजधानी
- ▁अधिक
- ▁भू
- ▁प्रति
- वून
- ▁भर
- ▁पाह
- ▁मी
- ▁ग्रंथ
- नुसार
- ▁श्री
- ग्रह
- ▁पूर्व
- ▁वर
- ोज
- ▁हिंदू
- ▁मुख्य
- ▁तयार
- लेले
- ▁कारण
- ▁करत
- ▁सांग
- ▁यांनी
- ुद्धा
- ▁चार
- ुक
- ▁दिस
- ▁वेळ
- ▁मात्र
- पुर
- ▁उत्
- ▁त्यात
- ▁की
- ▁कर्नाटक
- ▁जीवन
- ▁इतिहास
- ▁वाट
- स्थान
- ▁जन
- स्ट
- ▁काळात
- ▁जात
- मी
- ीचे
- '?'
- ▁चेन्नई
- '!'
- ▁शब्द
- ण्यास
- ▁मोठ
- ▁असतो
- ▁कृष्णा
- देव
- ▁उल्लेख
- ▁पुढे
- ▁गेला
- ▁गण
- ▁मध्य
- पूर्ण
- ▁प्रकार
- ▁बे
- ाशी
- ▁मह
- बंध
- ▁पृथ्वी
- ▁रावण
- ▁मार
- ामुळे
- ▁कर्ण
- ▁कृष्ण
- ▁करतात
- ▁त्यांच
- ▁मोठे
- ▁दिला
- ▁करा
- ▁लागत
- ▁गुरू
- ण्याची
- ▁संस्था
- वले
- ▁दक्षिण
- ▁परंतु
- ▁गाव
- ▁तरी
- संख्य
- ▁संस्कृती
- त्ता
- ▁झाल्या
- ▁दिवस
- ▁निवड
- ▁अनु
- ▁महाराष्ट्रातील
- कड
- ▁कार्य
- ▁ठ
- ▁फार
- ▁शिव
- ▁ठर
- व्यवस्थ
- ▁माग
- ताना
- ▁येते
- ▁मुंबई
- ▁ज्ञानेश्वर
- पेक्षा
- ग्र
- ▁सुरू
- ▁मोठा
- ▁जो
- स्व
- ▁नस
- ▁स्वतः
- ▁तेव्हा
- ▁राजस्थान
- ज्ञान
- राव
- पती
- ▁कोण
- ण्यात
- ▁बन
- बरोबर
- ▁डॉ
- प्रकाश
- ▁असून
- दर्श
- ▁वै
- मंत्र
- गाव
- ▁त्याचा
- ▁काय
- ▁साहित्य
- ▁तेथे
- णाऱ्या
- ▁असतात
- ▁कमी
- ▁जातात
- आ
- राज
- चीन
- ▁कर्
- ▁बनव
- ▁विद्यापीठ
- ▁कीर्तन
- ▁घेऊ
- ▁विचार
- ▁खेळ
- ▁टाक
- ▁पाच
- ▁भागात
- ष्ठ
- ▁खूप
- ▁मन
- ▁मार्ग
- ▁जास्त
- ▁काढ
- शिवाय
- ायला
- दार
- हर
- ▁घर
- ः
- ▁अमरावती
- ▁पश्चिम
- ▁केंद्र
- ▁माहिती
- त्त्व
- ▁यांचे
- ंपैकी
- ▁अंतर
- ▁बस
- उ
- ▁करण्याच
- ▁श्रीकृष्ण
- ▁साम्राज्य
- ▁हिंदी
- ▁नंतर
- ानंतर
- ▁कथा
- ापासून
- ▁शकत
- ▁प्रांत
- ▁येत
- वाड
- ▁लाव
- ▁तिच्या
- ▁घड
- ▁प्रमाण
- छ
- ▁अतिशय
- ▁इंग्रज
- ▁क्षेत्र
- ▁आढळत
- ▁राधा
- ▁समाज
- ▁गेली
- ▁लिहिल
- ट्ट
- ▁त्यानंतर
- ▁येतो
- ▁पांडव
- ▁गीत
- ाऱ्या
- पणे
- ▁यु
- ▁जाग
- ▁भ्रष्टाचार
- ▁समुद्र
- ▁चांगल
- ▁भीम
- ▁विभाग
- ▁जाऊ
- ▁घेतले
- वृत्त
- चंद्र
- ▁बर
- ▁भाव
- ▁माझ
- ।
- ▁क्रमांक
- ▁भीष्म
- ▁पत्नी
- बद्दल
- ▁प्रत्येक
- ▁पुस्तक
- ▁अभ्यास
- ▁ग्रीस
- ▁मंदिर
- ▁निर्मा
- ▁अवतार
- ▁पर्वत
- ▁राजकीय
- ▁महत्त्वाच
- ▁स्थापन
- ▁गंगा
- ▁डो
- ▁ऐ
- युक्त
- खाली
- ▁काव्य
- ▁संस्कृत
- ▁ओ
- ▁करतो
- ांमुळे
- ▁देख
- वरून
- ▁पूर्ण
- ▁अमेरिक
- ▁मृत्यू
- ▁ब्रह्म
- ▁अकोला
- ▁सांगितले
- च्छ
- ▁एकलव्य
- ▁मुलग
- ▁लागले
- ▁मूळ
- ▁नव्हत
- ▁दिली
- ▁पद्धत
- ▁असताना
- ▁फिर
- ▁चित्र
- ▁करणे
- ▁बाब
- ▁वृत्त
- ▁नावाने
- हार
- ▁भाज
- ▁द्रौपदी
- ▁ऋषी
- ▁विशेष
- ▁विश्व
- ▁विविध
- ▁लहान
- ▁बाजू
- ▁लावणी
- ▁लढ
- ▁यांना
- ाधिक
- ▁देत
- ांवर
- ▁नामदेव
- अ
- ▁ओळखल
- ँ
- ▁खाद्यपदार्थ
- ▁महाविद्यालय
- ▁म्हटले
- ▁रेल्वे
- ▁अध्यक्ष
- ▁कौरव
- ▁व्यक्ती
- ▁भाषेत
- ▁लक्ष्मण
- ▁पुणे
- ▁विवाह
- ▁केल्या
- ▁असत
- ▁माझ्या
- ▁लक्ष
- ▁पाणी
- ▁घाल
- भाग
- ▁देण्या
- ▁छोट
- ▁लोकप्रिय
- ▁शंतनू
- ▁प्रभाव
- ▁दाखव
- ▁बांध
- ▁बहु
- द्वार
- श्च
- ▁करीत
- नगर
- ▁द्व
- राष्ट्र
- ▁मिळव
- ▁काँग्रेस
- ▁जरासंध
- ▁भूगोल
- ▁केरळ
- ▁इराक
- ▁सिद्ध
- ▁आनंद
- ▁रचना
- ▁करण्यात
- ▁प्रेम
- ▁जुन
- र्जा
- ए
- पुत्र
- ▁पंतप्रधान
- ▁संस्थे
- ▁रावणाच
- ▁लेणी
- ▁नाटक
- ▁मुक्त
- ▁करणार
- ▁विषय
- ▁तुल
- ▁अर्जुना
- इ
- ष्ण
- पूर्व
- ▁दुर्योधन
- ▁दिल्ली
- ▁सापड
- ▁बुद्ध
- ▁असणार
- बोध
- ▁वेद
- ▁जिल्ह्या
- ▁पांडवां
- देख
- क्क
- कुल
- ▁भारताच
- ▁क्रिकेट
- ▁पुन्हा
- ▁ब्रिटिश
- ▁मच्छिंद्रनाथ
- ▁संशोधन
- ▁गोंधळ
- ▁सुरुवात
- ▁विष्णू
- ▁तुझ
- ▁प्रशास
- ▁पहिला
- ▁शिष्य
- ▁वडील
- ▁वंदे
- स्थाप
- ▁मिळाले
- भूमी
- ▁पर्यटन
- ▁संदर्भ
- ▁उच्च
- स्वयंवर
- ▁सगळ
- ▁आवड
- ▁एकमे
- ▁उंच
- ▁अर्जुन
- ओ
- विषयी
- ▁उपलब्ध
- ▁द्रोणाचार्य
- ▁वेगवेगळ
- ▁समावेश
- ▁एखाद
- ▁दिवशी
- ाध्यक्ष
- ▁प्राप्त
- ▁प्रयत्
- ▁वर्णन
- ▁तंत्रज्ञ
- ेश्वर
- ▁इंद्र
- ुष्क
- ▁दोन्ही
- ▁विजय
- ▁वस्तू
- पत्ती
- ▁महाराज
- ▁कधी
- ▁आंतर
- ▁आठव
- ▁अभि
- ▁मदत
- व्रत
- ▁शाळा
- ▁पाण्याच
- ाणिक
- भूत
- ;
- ▁पंजाब
- ▁ब्राह्मण
- ▁भूकंप
- ▁पाहिजे
- ▁सदस्य
- ▁युरोप
- ▁पहिल्या
- ▁वेगळ
- निर्मित
- ▁कोणत्या
- ▁राहिला
- ▁दुसर्
- ▁गोरक्षनाथ
- ▁गेल्या
- ▁गंगे
- सोबत
- ▁डाळ
- ▁पूज
- ▁अक्षर
- ▁त्रि
- ▁बदल
- ▁रामायणाच
- ▁पुरस्कार
- ▁मनोगत
- ▁प्रश्न
- मुख्या
- ध्यात्म
- ▁होईल
- ▁ऐकून
- ▁रशिया
- ▁नृत्य
- ▁गोष्टी
- ▁उत्तम
- ▁विद्या
- ▁शतका
- ▁ओळख
- ▁घातल
- ▁बोल
- ▁नद्या
- पैकी
- ▁स्वातंत्र्य
- ▁नैसर्गिक
- ▁प्रकल्प
- ▁कुटुंब
- ▁धार्मिक
- ▁नारायण
- ▁भौगोलिक
- ▁मातरम्
- ▁अभ्यासक्रम
- ▁स्वतंत्र
- ▁भगवान
- ▁मुख्यालय
- ▁दुसरा
- ▁संगीत
- सारखे
- ▁लिह
- ▁पोळी
- ▁अजून
- ▁साखर
- ▁वाहत
- ▁पसरल
- ंस्कृत
- तिहास
- ▁गोरक्ष
- '"'
- ▁उत्पादन
- ▁गहिनीनाथ
- ▁पराक्रम
- ▁पाकिस्तान
- ▁रुक्मिणी
- ▁सर्वोच्च
- ▁हनुमान
- ▁त्यावेळी
- दृष्ट्या
- ▁कंपनी
- ▁द्रोण
- ▁गांधी
- दरम्यान
- ▁आम्ही
- ▁बहुतेक
- ▁अश्व
- ▁चित्रपट
- ▁हिंदु
- ▁घटना
- ▁शक्ती
- ▁समाध
- ▁प्रसंग
- कुमार
- मार्ग
- ऋ
- ▁अश्वत्थामा
- ▁दुसऱ्या
- ▁मनुष्य
- ▁वऱ्हाड
- ▁इस्लाम
- ▁तांदूळ
- ▁पुढील
- ▁निर्णय
- ▁परंपरा
- ▁आकर्ष
- ▁खगोल
- विरुद्ध
- ▁व्यापार
- ▁माद्री
- ▁स्त्री
- ▁वडिल
- ▁भाषिक
- ▁शेवट
- ▁शबरी
- ▁प्रवेश
- ▁स्वीकार
- ▁पांडू
- ▁गडकर
- ▁पुण्य
- शाखा
- ▁सिक्कीम
- ▁ईशान्य
- ▁कादंबरी
- ▁गाडगेबाबा
- ▁तालुक्यात
- ▁परिषद
- ▁युधिष्ठिर
- ▁युध्द
- ▁व्यक्तिरेखा
- ▁अस्तित्व
- ▁इत्यादी
- ▁ख्रिस्त
- ▁धृतराष्ट्र
- ▁मृत्यु
- ▁वेरूळ
- ▁जिल्हा
- ▁गुजरात
- ▁नेहमी
- ▁जमिनी
- ▁पर्वतरांग
- ▁लग्न
- ▁सिंध
- ंद्रनाथ
- ▁कारखान
- सारखी
- ''''
- अण्णाद्रमुक
- ▁अभियांत्रिकी
- ▁गुरुत्वाकर्षण
- ▁हस्तिनापूरच
- ▁आधुनिक
- ▁जयललिता
- ▁खेळाडू
- ▁तत्त्वज्ञान
- ▁तालुका
- ▁दशरथा
- ▁भोवती
- ▁रूपांतर
- ऐ
- ़
- ':'
- '-'
- ॊ
- ॄ
- ॆ
- ॲ
- ऍ
- ‘
- ङ
- औ
- ऑ
- ऱ
- ऌ
- ऎ
- ञ
- ऽ
- ॓
- ॔
- ॥
init: null
input_size: null
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: null
    zero_infinity: true
    brctc_risk_strategy: exp
    brctc_group_strategy: end
    brctc_risk_factor: 0.0
joint_net_conf: null
use_preprocessor: true
use_lang_prompt: false
use_nlp_prompt: false
token_type: char
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
short_noise_thres: 0.5
aux_ctc_tasks: []
frontend: default
frontend_conf: {}
specaug: null
specaug_conf: {}
normalize: utterance_mvn
normalize_conf: {}
model: espnet
model_conf: {}
preencoder: null
preencoder_conf: {}
encoder: conformer
encoder_conf: {}
postencoder: null
postencoder_conf: {}
decoder: rnn
decoder_conf: {}
preprocessor: default
preprocessor_conf: {}
required:
- output_dir
- token_list
version: '202409'
distributed: false
